# this is the config for theme

# menu items appear on the header
menu:
    archives: /archives
    about: /about
    source: https://github.com/songziming/blog

# Links
links:
    "荒原": http://wcqblog.github.io/
    "Renfei Song": http://www.renfei.org/blog/
    "羽民": http://wanzy.me/blog/
    "峯少": http://timmyxu.me
    "渣诚": http://heavenduke.com

# Automatically Excerpt
auto_excerpt:
    enable: true
    length: 150

# disqus shortname, use false to disable it
disqus_shortname: szm

# google analytics tracking ID
ganalytics_id: UA-73870068-1
