title: Song Ziming's Blog
author: Song Ziming

url: http://blog.szm.me
root: /
permalink: /:title/

include: [".nojekyll"]
exclude: ["README.md", "deploy.sh"]

markdown: redcarpet
kramdown:
    input: GFM
redcarpet:
    extensions:
        - fenced_code_blocks
        - tables
sass:
    style: compressed
defaults:
    -
        scope:
            path: ""
        values:
            layout: "post"

menu:
    archives: /archives
    about: /about
    source: https://github.com/songziming/blog

disqus_shortname: szm
ganalytics_id: UA-73870068-1