site_name:   Reinvent the Wheel
site_author: Song Ziming

repo_name:   Github
repo_url:    https://github.com/songziming/blog

plugins: []
markdown_extensions:
    - codehilite

theme:
    name:       null
    custom_dir: writethedocs

nav:
    - "index.md"
    - "系统开发":
        - "osdev/lockless_console.md"
        - "osdev/page_frame_allocation.md"